// Step-by-step moves for each pattern
// parts: { text, highlight } — highlight=true renders in blue bold

const m = (num, parts) => ({ num, parts });
const p = (text, highlight = false) => ({ text, highlight });

export const PATTERN_MOVES = {
  'Saju Jirugi': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(2, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward B while executing a low block to B with the left forearm.')]),
    m(3, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(4, [p('Move the right foot to D forming a left '), p('Walking Stance', true), p(' toward C while executing a low block to C with the left forearm.')]),
    m(5, [p('Move the right foot to C forming a right '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the right fist.')]),
    m(6, [p('Move the right foot to B forming a left '), p('Walking Stance', true), p(' toward A while executing a low block to A with the left forearm.')]),
    m(7, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(8, [p('Move the left foot to A forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(9, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(10, [p('Move the left foot to C forming a right '), p('Walking Stance', true), p(' toward B while executing a low block to B with the right forearm.')]),
    m(11, [p('Move the left foot to B forming a left '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the left fist.')]),
    m(12, [p('Move the left foot to A forming a right '), p('Walking Stance', true), p(' toward C while executing a low block to C with the right forearm.')]),
    m(13, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist. Return to ready stance.')]),
  ],

  'Saju Makgi': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing an outer forearm low block to D.')]),
    m(2, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward B while executing an inner forearm middle block to B.')]),
    m(3, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing an outer forearm low block to B.')]),
    m(4, [p('Move the right foot to D forming a left '), p('Walking Stance', true), p(' toward C while executing an inner forearm middle block to C.')]),
    m(5, [p('Move the right foot to C forming a right '), p('Walking Stance', true), p(' toward C while executing an outer forearm low block to C.')]),
    m(6, [p('Move the right foot to B forming a left '), p('Walking Stance', true), p(' toward A while executing an inner forearm middle block to A.')]),
    m(7, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing an outer forearm low block to A.')]),
    m(8, [p('Move the left foot to A forming a right '), p('Walking Stance', true), p(' toward D while executing an inner forearm middle block to D.')]),
    m(9, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing an outer forearm low block to D.')]),
    m(10, [p('Move the left foot to C forming a right '), p('Walking Stance', true), p(' toward B while executing an inner forearm middle block to B.')]),
    m(11, [p('Move the left foot to B forming a left '), p('Walking Stance', true), p(' toward B while executing an outer forearm low block to B.')]),
    m(12, [p('Move the left foot to A forming a right '), p('Walking Stance', true), p(' toward C while executing an inner forearm middle block to C.')]),
    m(13, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing an outer forearm low block to C.')]),
    m(14, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward A while executing an inner forearm middle block to A.')]),
    m(15, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing an outer forearm low block to A. Return to ready stance.')]),
  ],

  'Chon-Ji': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward C while executing a low block to C with the left forearm.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(5, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a low block to B with the right forearm.')]),
    m(6, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(7, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a low block to A with the left forearm.')]),
    m(8, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(9, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(10, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(11, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward C while executing a low block to C with the left forearm.')]),
    m(12, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(13, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a low block to B with the right forearm.')]),
    m(14, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(15, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a low block to A with the left forearm.')]),
    m(16, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(17, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(18, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist. Return to ready stance.')]),
  ],

  'Dan-Gun': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right knifehand.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a high punch to D with the right fist.')]),
    m(3, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a high punch to D with the left fist.')]),
    m(4, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left knifehand.')]),
    m(5, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a high punch to C with the left fist.')]),
    m(6, [p('Move the right foot to C forming a right '), p('Walking Stance', true), p(' toward C while executing a high punch to C with the right fist.')]),
    m(7, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(8, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a high punch to D with the right fist.')]),
    m(9, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a high punch to D with the left fist.')]),
    m(10, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a high punch to D with the right fist.')]),
    m(11, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a rising block to A with the left forearm.')]),
    m(12, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a high punch to A with the left fist.')]),
    m(13, [p('Move the left foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a high punch to A with the right fist.')]),
    m(14, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a high punch to A with the left fist.')]),
    m(15, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a rising block to B with the right forearm.')]),
    m(16, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a high punch to B with the right fist.')]),
    m(17, [p('Move the left foot to B forming a left '), p('Walking Stance', true), p(' toward B while executing a high punch to B with the left fist.')]),
    m(18, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a high punch to B with the right fist.')]),
    m(19, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a rising block to C with the left forearm.')]),
    m(20, [p('Move the right foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a high punch to C with the left fist. Return to ready stance.')]),
  ],

  'Do-San': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(5, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(6, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(7, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the left forearm.')]),
    m(8, [p('Execute a '), p('front snap kick', true), p(' to D with the left foot, then land in a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(9, [p('Move the right foot to B forming a left '), p('L-Stance', true), p(' toward B while executing a middle block to B with the left knifehand.')]),
    m(10, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(11, [p('Move the left foot to A forming a right '), p('L-Stance', true), p(' toward A while executing a middle block to A with the right knifehand.')]),
    m(12, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(13, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(14, [p('Execute a '), p('front snap kick', true), p(' to D with the left foot, then land in a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(15, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(16, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(17, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(18, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a low block to A with the left forearm.')]),
    m(19, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(20, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(21, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(22, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist. Return to ready stance.')]),
  ],

  'Won-Hyo': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right knifehand.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left knifehand.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(5, [p('Move the left foot to D forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right knifehand.')]),
    m(6, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(7, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(8, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(9, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right knifehand.')]),
    m(10, [p('Execute a '), p('front snap kick', true), p(' to B with the left foot, then land in a left '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the left fist.')]),
    m(11, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left knifehand.')]),
    m(12, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(13, [p('Move the left foot to D forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right knifehand.')]),
    m(14, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(15, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(16, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(17, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left knifehand.')]),
    m(18, [p('Execute a '), p('front snap kick', true), p(' to A with the left foot, then land in a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(19, [p('Move the right foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right knifehand.')]),
    m(20, [p('Execute a '), p('front snap kick', true), p(' to B with the right foot, then land in a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(21, [p('Move the left foot to D forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right knifehand.')]),
    m(22, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(23, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(24, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(25, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left knifehand.')]),
    m(26, [p('Execute a '), p('front snap kick', true), p(' to A with the left foot, then land in a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist. Return to ready stance.')]),
  ],

  'Yul-Gok': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(5, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(6, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(7, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(8, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(9, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(10, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(11, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(12, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(13, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(14, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(15, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(16, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(17, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a low block to A with the left forearm.')]),
    m(18, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(19, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(20, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(21, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(22, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(23, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(24, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(25, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(26, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(27, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(28, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(29, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a low block to A with the left forearm.')]),
    m(30, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(31, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(32, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(33, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(34, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(35, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(36, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(37, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm. Return to ready stance.')]),
  ],

  'Joong-Gun': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(5, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(6, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(7, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(8, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(9, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(10, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(11, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(12, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(13, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(14, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(15, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(16, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(17, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a rising block to A with the left forearm.')]),
    m(18, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(19, [p('Move the left foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(20, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(21, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a rising block to B with the right forearm.')]),
    m(22, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(23, [p('Move the left foot to B forming a left '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the left fist.')]),
    m(24, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(25, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a rising block to C with the left forearm.')]),
    m(26, [p('Move the right foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(27, [p('Move the left foot to C forming a right '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the right fist.')]),
    m(28, [p('Move the right foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(29, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(30, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(31, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist. Return to ready stance.')]),
  ],

  'Toi-Gye': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(5, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(6, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(7, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(8, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(9, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(10, [p('Execute a '), p('turning kick', true), p(' to B with the right foot, then land in a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(11, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(12, [p('Execute a '), p('turning kick', true), p(' to A with the left foot, then land in a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(13, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(14, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(15, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(16, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(17, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a rising block to A with the left forearm.')]),
    m(18, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(19, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(20, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(21, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(22, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(23, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(24, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(25, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(26, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(27, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(28, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(29, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(30, [p('Execute a '), p('turning kick', true), p(' to B with the right foot, then land in a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(31, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(32, [p('Execute a '), p('turning kick', true), p(' to A with the left foot, then land in a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(33, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(34, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(35, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(36, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist. Return to ready stance.')]),
  ],

  'Hwa-Rang': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(5, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(6, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(7, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(8, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(9, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(10, [p('Execute a '), p('turning kick', true), p(' to B with the right foot, then land in a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(11, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(12, [p('Execute a '), p('turning kick', true), p(' to A with the left foot, then land in a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(13, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(14, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(15, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(16, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(17, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a rising block to A with the left forearm.')]),
    m(18, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(19, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(20, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(21, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(22, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(23, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(24, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(25, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(26, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(27, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(28, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist. Return to ready stance.')]),
  ],

  'Choong-Moo': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(5, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(6, [p('Execute a '), p('flying front kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(7, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(8, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(9, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(10, [p('Execute a '), p('reverse turning kick', true), p(' to B with the right foot, then land in a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(11, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(12, [p('Execute a '), p('reverse turning kick', true), p(' to A with the left foot, then land in a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(13, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(14, [p('Execute a '), p('flying front kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(15, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(16, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(17, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a rising block to A with the left forearm.')]),
    m(18, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(19, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(20, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(21, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward D while executing a middle block to D with the right inner forearm.')]),
    m(22, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(23, [p('Move the right foot to A forming a left '), p('L-Stance', true), p(' toward C while executing a middle block to C with the left inner forearm.')]),
    m(24, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a middle punch to C with the left fist.')]),
    m(25, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(26, [p('Execute a '), p('flying front kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(27, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(28, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(29, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm. Return to ready stance.')]),
  ],

  'Kwang-Gae': [
    m(0, [p('Parallel Ready Stance', true), p(' facing D')]),
    m(1, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(2, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a high punch to D with the right fist.')]),
    m(3, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward C while executing a rising block to C with the left forearm.')]),
    m(4, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a high punch to C with the left fist.')]),
    m(5, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(6, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(7, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(8, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(9, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(10, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(11, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(12, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(13, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(14, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(15, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(16, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(17, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a low block to A with the left forearm.')]),
    m(18, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(19, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(20, [p('Move the right foot to A forming a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist.')]),
    m(21, [p('Move the left foot to B forming a right '), p('Walking Stance', true), p(' toward D while executing a rising block to D with the right forearm.')]),
    m(22, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a high punch to D with the right fist.')]),
    m(23, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward C while executing a rising block to C with the left forearm.')]),
    m(24, [p('Move the left foot to C forming a left '), p('Walking Stance', true), p(' toward C while executing a high punch to C with the left fist.')]),
    m(25, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(26, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(27, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(28, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(29, [p('Move the left foot to B forming a right '), p('L-Stance', true), p(' toward B while executing a middle block to B with the right inner forearm.')]),
    m(30, [p('Move the right foot to B forming a right '), p('Walking Stance', true), p(' toward B while executing a middle punch to B with the right fist.')]),
    m(31, [p('Move the left foot to A forming a left '), p('L-Stance', true), p(' toward A while executing a middle block to A with the left inner forearm.')]),
    m(32, [p('Move the right foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the left fist.')]),
    m(33, [p('Move the left foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a low block to D with the right forearm.')]),
    m(34, [p('Execute a '), p('front snap kick', true), p(' to D with the right foot, then land in a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(35, [p('Move the left foot to D forming a left '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the left fist.')]),
    m(36, [p('Move the right foot to D forming a right '), p('Walking Stance', true), p(' toward D while executing a middle punch to D with the right fist.')]),
    m(37, [p('Move the left foot to A forming a left '), p('Walking Stance', true), p(' toward A while executing a low block to A with the left forearm.')]),
    m(38, [p('Execute a '), p('front snap kick', true), p(' to A with the right foot, then land in a right '), p('Walking Stance', true), p(' toward A while executing a middle punch to A with the right fist. Return to ready stance.')]),
  ],
};

export default PATTERN_MOVES;
